version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: remitflow-postgres
    restart: always
    environment:
      POSTGRES_USER: remitflow
      POSTGRES_PASSWORD: remitflow_password
      POSTGRES_DB: remitflow_db
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
